version: '3'
services:
    test-int-db:
        image: postgres:12
        ports:
            - 5454:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: nestjs
